(function(g){var window=this;var iwa=function(a,b){var c=[];g.Cl(b,function(a){try{var b=g.nD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.mD(b)&&c.push(a):c.push(a)},a);
return c},jwa=function(a,b){var c=iwa(a,b);
(0,g.H)(c,function(a){g.nD.prototype.remove.call(this,a)},a)},F8=function(a,b){g.U0.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.U=a;this.F={};this.R(a,"onMdxReceiversChange",this.J);this.R(a,"presentingplayerstatechange",this.J);this.J()},kwa=function(){var a=g.KG;
jwa(a,a.g.Td(!0))},G8=function(a){g.mH.call(this,"ScreenServiceProxy");
this.cd=a;this.o=[];this.o.push(this.cd.$_s("screenChange",(0,g.B)(this.nT,this)));this.o.push(this.cd.$_s("onlineScreenChange",(0,g.B)(this.yP,this)))},H8=function(a){g.$G("cloudview",a)},lwa=function(a){H8("setApiReady_ "+a);
g.v("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},mwa=function(a){g.bG[a]&&(a=g.bG[a],(0,g.H)(a,function(a){g.$F[a]&&delete g.$F[a]}),a.length=0)},J8=function(){return g.x("yt.mdx.remote.connection_")},K8=function(a){g.v("yt.mdx.remote.connectData_",a,void 0)},nwa=function(a){g.v("yt.mdx.remote.currentScreenId_",a,void 0)},L8=function(){return g.x("yt.mdx.remote.currentScreenId_")},N8=function(){if(!M8){var a=g.x("yt.mdx.remote.screenService_");
M8=a?new G8(a):null}return M8},O8=function(a){g.v("yt.mdx.remote.cloudview.initializing_",a,void 0)},P8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Q8=function(a){H8("setCastInstalled_ "+a);
g.MG("yt-remote-cast-installed",a)},R8=function(a){g.$G("cloudview",a)},owa=function(a,b){I8().init(a,b)},S8=function(){return!!g.NG("yt-remote-cast-installed")},pwa=function(){H8("dispose");
var a=I8();a&&a.dispose();g.v("yt.mdx.remote.cloudview.instance_",null,void 0);lwa(!1);g.dG(T8);T8.length=0},qwa=function(){var a=window.document.createElement("a");
g.Fd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Sa(a)},rwa=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},swa=function(a){var b=g.ZF();
if(b)if(b.clear(a),a)mwa(a);else for(var c in g.bG)mwa(c)},U8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},W8=function(a){var b=J8();
K8(null);a||nwa("");g.v("yt.mdx.remote.connection_",a,void 0);V8&&((0,g.H)(V8,function(b){b(a)}),V8.length=0);
b&&!a?g.gG("yt-remote-connection-change",!1):!b&&a&&g.gG("yt-remote-connection-change",!0)},twa=function(){return g.x("yt.mdx.remote.connectData_")},X8=function(){var a=L8();
if(!a)return null;var b=N8().ae();return g.lH(b,a)},uwa=function(a,b){Q8(!0);
O8(!1);owa(a,function(a){a?(lwa(!0),g.eG("yt-remote-cast2-api-ready")):(R8("Failed to initialize cast API."),Q8(!1),g.OG("yt-remote-cast-available"),g.OG("yt-remote-cast-receiver"),pwa());b(a)})},vwa=function(){return S8()?I8()?I8().getCastSession():(R8("getCastSelector: Cast is not initialized."),null):(R8("getCastSelector: Cast API is not installed!"),null)},wwa=function(){var a=qwa(),b=window.document.getElementById(a),c=b&&g.oF(b,"loaded");
c||b&&!c||(b=rwa(a,function(){g.oF(b,"loaded")||(g.pF(b,"loaded","true"),g.eG(a),g.wE(g.za(swa,a),0))}))},xwa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},ywa=function(){if(g.lpa){var a=2,b=g.Ah(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Fh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Ch,c)}},Z8=function(a,b){L8();
X8()&&X8();nwa(a.id);var c=new g.qI(Y8,a,U8());c.connect(b,twa());c.subscribe("beforeDisconnect",function(a){g.gG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){J8()&&(J8(),W8(null))});
W8(c)},$8=function(){var a=g.rH();
if(!a)return null;var b=N8().ae();return g.lH(b,a)},a9=function(a){g.$G("remote",a)},b9=function(){var a=J8();
return!!a&&3!=a.getProxyState()},c9=function(){P8()?I8().stopSession():R8("stopSession called before API ready.");
var a=J8();a&&(a.disconnect(1),W8(null))},zwa=function(){var a=N8().cd.$_gos();
var b=X8();b&&J8()&&(g.kH(a,b)||a.push(b));return xwa(a)},e9=function(a,b){g.QF.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.BB;this.A=this.o=null;this.J=(0,g.B)(this.EN,this);this.F=(0,g.B)(this.il,this);this.G=(0,g.B)(this.DN,this);this.K=(0,g.B)(this.RN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.pu,this),Awa(this))):c=3;0!=c&&(b?this.pu(c):g.wE((0,g.B)(function(){this.pu(c)},this),0));
var d=vwa();d&&d9(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},f9=function(a){return new g.fI(a.B.getPlayerContextData())},Bwa=function(a,b,c,d,e){var f=f9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.jI(f,b,d);g.t(c)&&(g.hI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);g9(a,"setPlaylist",l);e||h9(a,f)},Awa=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.za(this.QP,a),this))},a)},Cwa=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},i9=function(a,b){50>a.C.Kc()&&g.DB(a.C,b)},j9=function(a,b,c){var d=f9(a);
g.hI(d,c);-1E3!=d.g&&(d.g=b);h9(a,d)},g9=function(a,b,c){a.B.sendMessage(b,c)},h9=function(a,b){Cwa(a);
a.B.setPlayerContextData(g.kI(b));Awa(a)},d9=function(a,b){a.A&&(a.A.removeUpdateListener(a.J),a.A.removeMediaListener(a.F),a.il(null));
a.A=b;a.A&&(k9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.J),a.A.addMediaListener(a.F),a.A.media.length&&a.il(a.A.media[0]))},Dwa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=f9(a);b.contentId!=d.videoId&&k9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.hI(d,a.o.getEstimatedTime());h9(a,d)}else k9("No cast media video. Ignoring state update.")},k9=function(a){g.$G("CP",a)},l9=function(a,b,c){return(0,g.B)(function(a){this.jc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.jc("Retrying "+b+" using MDx browser channel."),g9(this,b,c))},a)},Ewa=function(a,b){var c=!1;
I8()||(c=new g.$H(a,b),c.subscribe("yt-remote-cast2-availability-change",function(a){g.MG("yt-remote-cast-available",a);g.gG("yt-remote-cast2-availability-change",a)}),c.subscribe("yt-remote-cast2-receiver-selected",function(a){H8("onReceiverSelected: "+a.friendlyName);
g.MG("yt-remote-cast-receiver",a);g.gG("yt-remote-cast2-receiver-selected",a)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(a){H8("onReceiverResumed: "+a.friendlyName);
g.MG("yt-remote-cast-receiver",a)}),c.subscribe("yt-remote-cast2-session-change",function(a){H8("onSessionChange: "+g.hH(a));
a||g.OG("yt-remote-cast-receiver");g.gG("yt-remote-cast2-session-change",a)}),g.v("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
H8("cloudview.createSingleton_: "+c);return c},Fwa=function(){var a=0<=g.Gb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.TE||a},m9=function(a,b){P8()?I8().setConnectedScreenStatus(a,b):R8("setConnectedScreenStatus called before ready.")},Gwa=function(){H8("clearCurrentReceiver");
g.OG("yt-remote-cast-receiver")},Hwa=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){ywa();a({command:"cast.sender.init"});return}}if(window.chrome)if(ywa(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.yh();55<=b?a="55":50<=b&&(a="50");g.Fh("//www.gstatic.com/eureka/clank"+a+g.Dh,g.Ch)}else g.Gh(0);else g.Ch()},Iwa=function(a){a?(g.MG("yt-remote-session-app",a.app),g.MG("yt-remote-session-name",a.name)):(g.OG("yt-remote-session-app"),g.OG("yt-remote-session-name"));
g.v("yt.mdx.remote.channelParams_",a,void 0)},Jwa=function(){var a=U8();
if(g.Tb(a)){var a=g.qH(),b=g.NG("yt-remote-session-name")||"",c=g.NG("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.v("yt.mdx.remote.channelParams_",a,void 0)}},Kwa=function(){var a=$8();
a?(a9("Resume connection to: "+g.hH(a)),Z8(a,0)):(g.zH(),Gwa(),a9("Skipping connecting because no session screen found."))},Lwa=function(a){a9("remote.onCastSessionChange_: "+g.hH(a));
if(a){var b=X8();b&&b.id==a.id?m9(b.id,"YouTube TV"):(b&&c9(),Z8(a,1))}else J8()&&c9()},Mwa=function(){var a=zwa(),b=X8();
b||(b=$8());return g.Za(a,function(a){return b&&g.eH(b,a.key)?!0:!1})},Nwa=function(){var a=g.NG("yt-remote-cast-receiver");
return a?a.friendlyName:null},Owa=function(a,b,c,d,e){Fwa()?Ewa(b,e)&&(O8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?uwa(a,c):(window.__onGCastApiAvailable=function(b,d){b?uwa(a,c):(R8("Failed to load cast API: "+d),Q8(!1),O8(!1),g.OG("yt-remote-cast-available"),g.OG("yt-remote-cast-receiver"),pwa(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):wwa():Hwa())):H8("Cannot initialize because not running Chrome")},
Pwa=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.tg(a)||"";b&&(this.port=":"+b);this.domain=g.sg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ra(a,"10.0")&&(this.o=!1))},Qwa=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);
return c},n9=function(){var a=Mwa();
!a&&S8()&&Nwa()&&(a={key:"cast-selector-receiver",name:Nwa()});return a},Rwa=function(){var a=zwa();
S8()&&g.NG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Swa=function(a){var b={device:"Desktop",
app:"youtube-desktop"},b=g.ND("MDX_CONFIG")||b;g.KG&&kwa();g.tH();Y8||(Y8=new Pwa(b?b.loungeApiHost:void 0),g.BH()&&(Y8.g="/api/loungedev"));V8||(V8=g.x("yt.mdx.remote.deferredProxies_")||[],g.v("yt.mdx.remote.deferredProxies_",V8,void 0));Jwa();var c=N8();if(!c){var d=new g.MH(Y8);g.v("yt.mdx.remote.screenService_",d,void 0);c=N8();Owa(a,d,function(a){a?L8()&&m9(L8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.gG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript),
b?b.appId:void 0)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.v("yt.mdx.remote.initialized_",!0,void 0),a9("Initializing: "+g.kg(b)),o9.push(g.cG("yt-remote-cast2-availability-change",function(){g.gG("yt-remote-receiver-availability-change")})),o9.push(g.cG("yt-remote-cast2-receiver-selected",function(){K8(null);
g.gG("yt-remote-auto-connect","cast-selector-receiver")})),o9.push(g.cG("yt-remote-cast2-receiver-resumed",function(){g.gG("yt-remote-receiver-resumed","cast-selector-receiver")})),o9.push(g.cG("yt-remote-cast2-session-change",Lwa)),o9.push(g.cG("yt-remote-connection-change",function(a){a?m9(L8(),"YouTube TV"):$8()||(m9(null,null),Gwa())})),a=U8(),b.isAuto&&(a.id+="#dial"),g.ZE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),a9(" -- with channel params: "+
g.kg(a)),Iwa(a),c.start(),L8()||Kwa())},p9=function(){S8()?I8()?P8()?(H8("Requesting cast selector."),I8().requestSession()):(H8("Wait for cast API to be ready to request the session."),T8.push(g.cG("yt-remote-cast2-api-ready",p9))):R8("requestCastSelector: Cast is not initialized."):R8("requestCastSelector: Cast API is not installed!")},q9=function(a,b,c){g.N.call(this);
this.F=a;this.U=b;this.o=new g.NF(this);g.O(this,this.o);this.o.R(b,"onCaptionsTrackListChanged",this.RO);this.o.R(b,"captionschanged",this.CN);this.o.R(b,"captionssettingschanged",this.gC);this.o.R(b,"videoplayerreset",this.ho);this.o.R(b,"mdxautoplaycancel",this.wG);this.O=this.o.R(b,"onVolumeChange",this.DA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.OA,this);c.subscribe("remotePlayerChange",this.ll,this);c.subscribe("remoteQueueChange",this.ho,this);c.subscribe("autoplayUpNext",this.qA,
this);c.subscribe("previousNextChange",this.LA,this);c.subscribe("nowAutoplaying",this.EA,this);c.subscribe("autoplayDismissed",this.pA,this);this.suggestion=null;this.G=new g.TJ(64);this.A=new g.pt(this.bC,500,this);g.O(this,this.A);this.B=new g.pt(this.cC,1E3,this);g.O(this,this.B);this.C={};this.K=new g.pt(this.uC,1E3,this);g.O(this,this.K);this.J=new g.ak(this.xL,1E3,this);g.O(this,this.J);this.M=g.y;this.gC();this.ho();this.ll()},r9=function(a,b){var c=a.F,d=a.U.ia().lengthSeconds;
c.J=b||0;c.g.Y("progresssync",b,d)},Twa=function(a){r9(a,0);
a.A.stop();s9(a,new g.TJ(64))},u9=function(a,b){if(t9(a)&&!a.D){var c=null;
b&&(c={style:a.U.ji()},g.ac(c,b));a.g.VB(a.U.ia().videoId,c);a.C=f9(a.g).o}},v9=function(a,b){var c=a.U.Pf();
c?Bwa(a.g,a.U.ia().videoId,b,c.Yd(),c.listId.toString()):Bwa(a.g,a.U.ia().videoId,b);s9(a,new g.TJ(1))},Uwa=function(a,b){if(b){var c=a.U.yc("captions","tracklist",{my:1});
c&&c.length?(a.U.Dd("captions","track",b),a.D=!1):(a.U.Rk("captions"),a.D=!0)}else a.U.Dd("captions","track",{})},t9=function(a){return f9(a.g).videoId==a.U.ia().videoId},s9=function(a,b){a.B.stop();
var c=a.G;if(!g.ZJ(c,b)){var d=g.W(b,2);if(d!=g.W(a.G,2)){var e=a.U;g.c2(e.app,d,e.playerType)}a.G=b;Vwa(a.F,c,b)}},w9=function(a){g.X.call(this,{H:"div",
N:"ytp-remote",L:[{H:"div",N:"ytp-remote-display-status",L:[{H:"div",N:"ytp-remote-display-status-icon",L:[g.SD()]},{H:"div",N:"ytp-remote-display-status-text",L:["{{statustext}}"]}]}]});this.o=new g.KV(this,250);g.O(this,this.o);this.A=a;this.R(a,"presentingplayerstatechange",this.B);Wwa(this,g.UU(a))},Wwa=function(a,b){if(3==a.A.Wa()){var c={RECEIVER_NAME:a.A.yc("remote","currentReceiver").name},c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.xb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",
c);
a.Fa("statustext",c);a.o.show()}else a.o.hide()},x9=function(a){g.zV.call(this,a);
this.A={key:g.jH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.K=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.TJ(64);this.J=0;var b=g.NU(a).D;b&&(b=b.A&&b.A.g)&&(b=new F8(a,b),g.O(this,b));b=new w9(a);g.O(this,b);g.oV(a,b.element,5)},Vwa=function(a,b,c){a.F=c;
a.g.Y("presentingplayerstatechange",new g.dK(c,b))},y9=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)c9();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ia().videoId;if(c||d){var e=a.g.Pf();if(e){var f=[];for(var k=0;k<e.getLength();k++)f[k]=e.gc(k).videoId}else f=[a.g.ia().videoId];c={videoIds:f,listId:c,videoId:d,index:Math.max(a.g.Xy(),0),currentTime:a.g.getCurrentTime()}}else c=null;a9("Connecting to: "+g.kg(b));"cast-selector-receiver"==b.key?(K8(c||null),c=c||null,P8()?I8().setLaunchParams(c):R8("setLaunchParams called before ready.")):!c&&b9()&&L8()==b.key?g.gG("yt-remote-connection-change",!0):
(c9(),K8(c||null),c=N8().ae(),(c=g.lH(c,b.key))&&Z8(c,1))}};
g.p(F8,g.U0);F8.prototype.J=function(){var a=this.U.yc("remote","receivers");a&&1<a.length&&!this.U.yc("remote","quickCast")?(this.F=g.Cb(a,this.B,this),g.W0(this,(0,g.I)(a,this.B)),a=this.U.yc("remote","currentReceiver"),g.V0(this,this.B(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.B=function(a){return a.key};
F8.prototype.hf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
F8.prototype.rd=function(a){g.U0.prototype.rd.call(this,a);this.U.Dd("remote","currentReceiver",this.F[a]);this.A.Rb()};
g.D(G8,g.mH);g.h=G8.prototype;g.h.ae=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.cp=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.Lo=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.cd.$_ubk(this.o[a]);this.o.length=0;this.cd=null;G8.aa.X.call(this)};
g.h.nT=function(){this.Y("screenChange")};
g.h.yP=function(){this.Y("onlineScreenChange")};
var M8=null,T8=[],V8=null,Y8=null;g.D(e9,g.QF);g.h=e9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,l9(this,"play")):g9(this,"play"),j9(this,1,g.iI(f9(this))),this.Y("remotePlayerChange")):i9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,l9(this,"pause")):g9(this,"pause"),j9(this,2,g.iI(f9(this))),this.Y("remotePlayerChange")):i9(this,this.pause)};
g.h.GC=function(a){if(1==this.g){if(this.o){var b=f9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.xb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,l9(this,"seekTo",{newTime:a}))}else g9(this,"seekTo",{newTime:a});j9(this,3,a);this.Y("remotePlayerChange")}else i9(this,g.za(this.GC,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,l9(this,"stopVideo")):g9(this,"stopVideo");var a=f9(this);a.index=-1;a.videoId="";g.gI(a);h9(this,a);this.Y("remotePlayerChange")}else i9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=f9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.B)(function(){k9("set receiver volume: "+d)},this),(0,g.B)(function(){this.jc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.B)(function(){k9("set receiver muted: "+b)},this),(0,g.B)(function(){this.jc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);g9(this,"setVolume",e)}c.muted=b;c.volume=a;h9(this,c)}else i9(this,g.za(this.setVolume,a,b))};
g.h.VB=function(a,b){if(1==this.g){var c=f9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.kg(b.style),g.ac(d,c.o));g9(this,"setSubtitlesTrack",d);h9(this,c)}else i9(this,g.za(this.VB,a,b))};
g.h.ou=function(a,b){if(1==this.g){g9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Sc.id});var c=f9(this);c.audioTrackId=b.Sc.id;h9(this,c)}else i9(this,g.za(this.ou,a,b))};
g.h.FC=function(a,b){if(1==this.g){if(a&&b){var c=f9(this);g.jI(c,a,b);h9(this,c)}g9(this,"previous")}else i9(this,g.za(this.FC,a,b))};
g.h.EC=function(a,b){if(1==this.g){if(a&&b){var c=f9(this);g.jI(c,a,b);h9(this,c)}g9(this,"next")}else i9(this,g.za(this.EC,a,b))};
g.h.Mw=function(){1==this.g?g9(this,"dismissAutoplay"):i9(this,this.Mw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.Y("proxyStateChange",a,this.g)}e9.aa.dispose.call(this)};
g.h.X=function(){Cwa(this);this.B=null;this.C.clear();d9(this,null);e9.aa.X.call(this)};
g.h.pu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.Y("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.EB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.QP=function(a,b){this.Y(a,b)};
g.h.EN=function(a){if(!a)this.il(null),d9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=f9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,h9(this,b)}};
g.h.il=function(a){k9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Dwa(this),this.Y("remotePlayerChange")};
g.h.DN=function(a){a?(Dwa(this),this.Y("remotePlayerChange")):this.il(null)};
g.h.RN=function(){var a=vwa();a&&d9(this,a)};
g.h.jc=function(a){g.$G("CP",a)};
var o9=[];g.h=Pwa.prototype;g.h.Wh=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Ag(b+a,{})};
g.h.nu=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Nb:g.za(this.iT,c,!0),onError:g.za(this.hT,d),ed:g.za(this.jT,d)};b&&(c.Sb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.JE(a,c)};
g.h.iT=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.hT=function(a,b){a(Error("Request error: "+b.status))};
g.h.jT=function(a){a(Error("request timed out"))};
g.p(q9,g.N);g.h=q9.prototype;g.h.X=function(){g.N.prototype.X.call(this);this.A.stop();this.B.stop();this.M();this.g.unsubscribe("proxyStateChange",this.OA,this);this.g.unsubscribe("remotePlayerChange",this.ll,this);this.g.unsubscribe("remoteQueueChange",this.ho,this);this.g.unsubscribe("autoplayUpNext",this.qA,this);this.g.unsubscribe("previousNextChange",this.LA,this);this.g.unsubscribe("nowAutoplaying",this.EA,this);this.g.unsubscribe("autoplayDismissed",this.pA,this);this.g=this.F=null};
g.h.uz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(t9(this)){if(1081!=f9(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":f9(this.g).xb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.Yi(c[0],c[1]);break;case "control_subtitles_set_track":u9(this,c[0]);break;case "control_set_audio_track":c=c[0],t9(this)&&this.g.ou(this.U.ia().videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":v9(this,this.U.getCurrentTime());break;case "control_seek":v9(this,c[0]);break;case "control_subtitles_set_track":u9(this,c[0]);break;case "control_set_audio_track":c=c[0],t9(this)&&this.g.ou(this.U.ia().videoId,c)}};
g.h.CN=function(a){this.uz("control_subtitles_set_track",g.Tb(a)?null:a)};
g.h.gC=function(){var a=this.U.yc("captions","track");g.Tb(a)||u9(this,a)};
g.h.DA=function(a){if(t9(this)){this.g.unsubscribe("remotePlayerChange",this.ll,this);var b=Math.round(a.volume);a=!!a.muted;var c=f9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.ll,this)}};
g.h.RO=function(){g.Tb(this.C)||Uwa(this,this.C);this.D=!1};
g.h.OA=function(a,b){this.B.stop();2==b&&this.cC()};
g.h.ll=function(){if(t9(this)){this.A.stop();var a=f9(this.g);switch(a.g){case 1081:s9(this,new g.TJ(8));break;case 1:this.bC();s9(this,new g.TJ(8));break;case 1083:case 3:s9(this,new g.TJ(9));break;case 0:s9(this,new g.TJ(2));this.J.stop();r9(this,this.U.ia().lengthSeconds);break;case 1082:s9(this,new g.TJ(4));break;case 2:s9(this,new g.TJ(4));r9(this,g.iI(a));break;case -1:s9(this,new g.TJ(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},s9(this,new g.TJ(128,
a))}var a=f9(this.g).o,b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,Uwa(this,a));a=f9(this.g);-1==a.volume||Math.round(this.U.getVolume())==a.volume&&this.U.Ie()==a.muted||this.K.isActive()||this.uC()}else Twa(this)};
g.h.LA=function(){this.U.Y("mdxpreviousnextchange")};
g.h.ho=function(){t9(this)||Twa(this)};
g.h.wG=function(){this.g.Mw()};
g.h.qA=function(a){a&&(a=g.JE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Nb:(0,g.B)(this.RQ,this)}))&&(this.M=(0,g.B)(a.abort,a))};
g.h.RQ=function(a,b){var c=new g.oQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.U.Y("mdxautoplayupnext",c)};
g.h.EA=function(a){(0,window.isNaN)(a)||this.U.Y("mdxnowautoplaying",a)};
g.h.pA=function(){this.U.Y("mdxautoplaycanceled")};
g.h.xL=function(a,b){-1==f9(this.g).g?v9(this,a):b&&this.g.GC(a)};
g.h.uC=function(){if(t9(this)){var a=f9(this.g);this.o.Da(this.O);a.muted?this.U.mute():this.U.vg();this.U.setVolume(a.volume);this.O=this.o.R(this.U,"onVolumeChange",this.DA)}};
g.h.bC=function(){this.A.stop();if(!this.g.na()){var a=f9(this.g);a.xb()&&s9(this,new g.TJ(8));r9(this,g.iI(a));this.A.start()}};
g.h.cC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(w9,g.X);w9.prototype.B=function(a){Wwa(this,a.state)};g.p(x9,g.zV);g.h=x9.prototype;g.h.create=function(){Swa("embedded"==g.Y(this.g).g);this.D.push(g.cG("yt-remote-before-disconnect",this.zN,this));this.D.push(g.cG("yt-remote-connection-change",this.aQ,this));this.D.push(g.cG("yt-remote-receiver-availability-change",this.MA,this));this.D.push(g.cG("yt-remote-auto-connect",this.YP,this));this.D.push(g.cG("yt-remote-receiver-resumed",this.XP,this));this.MA()};
g.h.load=function(){this.g.fq();g.zV.prototype.load.call(this);this.C=new q9(this,this.g,this.o);var a=twa(),a=a?a.currentTime:0,b=b9()?new e9(J8(),void 0):null;0==a&&b&&(a=g.iI(f9(b)));0!=a&&(this.J=a||0,this.g.Y("progresssync",a,void 0));Vwa(this,this.F,this.F);g.h2(this.g.app,6)};
g.h.unload=function(){this.g.Y("mdxautoplaycanceled");this.B=this.A;g.Ke(this.C,this.o);this.o=this.C=null;g.zV.prototype.unload.call(this);g.h2(this.g.app,5)};
g.h.X=function(){g.dG(this.D);g.zV.prototype.X.call(this)};
g.h.Wk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.uz.apply(this.C,[].concat([a],c instanceof Array?c:Qwa(g.ka(c))))};
g.h.iH=function(){return this.loaded?this.C.suggestion:null};
g.h.Hf=function(){return this.o?f9(this.o).Hf:!1};
g.h.hasNext=function(){return this.o?f9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.jL=function(){var a=f9(this.o),b=this.g.ia();return{allowSeeking:this.g.Md(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+((0,g.G)()-a.A)/1E3:a.C,isPeggedToLive:1>=(a.F?a.B+((0,g.G)()-a.A)/1E3:a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+((0,g.G)()-a.A)/1E3:a.B,seekableStart:0<a.D?a.D+((0,g.G)()-a.A)/1E3:a.D}};
g.h.kL=function(){this.o&&this.o.EC()};
g.h.lL=function(){this.o&&this.o.FC()};
g.h.zN=function(a){1==a&&(this.K=this.o?f9(this.o):null)};
g.h.aQ=function(){var a=b9()?new e9(J8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Je(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.ia().videoId&&this.g.Vy(a.videoId,g.iI(a)));this.g.Y("videodatachange","newdata",this.g.ia(),3)};
g.h.MA=function(){this.G=[this.A].concat(Rwa());var a=n9()||this.A;y9(this,a);this.g.ya("onMdxReceiversChange")};
g.h.YP=function(){var a=n9();y9(this,a)};
g.h.XP=function(){this.B=n9()};
g.h.iL=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?p9():y9(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&p9(),!0):!1}};
g.h.mL=function(){g9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Fd=function(){return!1};window._exportCheck==g.Ba&&g.v("ytmod.player.remote",x9,void 0);})(_yt_player);
